import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.scss";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import Content from "@/components/ui/Content";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "CRUD With NextJs",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header />
                <div className="container">
                    <Content>{children}</Content>
                </div>
                <Footer />
                <ToastContainer />
            </body>
        </html>
    );
}
