import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/componentLayout/Header";
import AppProvider from "@/app/AppProvider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = cookies();
    const accessToken = cookieStore.get("access_token")?.value;
    console.log(accessToken);

    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                <AppProvider initialAccessToken={accessToken}>
                    {children}
                </AppProvider>
            </body>
        </html>
    );
}
