import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/componentLayout/Header";

import { cookies } from "next/headers";
import AppProvider from "@/app/AppProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = cookies();
    const accessToken = cookieStore.get("access_token")?.value;
    const publicInfo = cookieStore.get("public_info")?.value;

    return (
        <html lang="en">
            <body className={inter.className}>
                <AppProvider
                    initialAccessToken={accessToken}
                    initPublicInfo={publicInfo}
                >
                    <Header />
                    {children}
                </AppProvider>
            </body>
        </html>
    );
}
