import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/componentLayout/Header";

import { cookies } from "next/headers";
import AppProvider from "@/app/AppProvider";
import { AuthProvider } from "@/components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = cookies();
    const accessToken = cookieStore.get("access_token")?.value;

    console.log("check");

    return (
        <html lang="en">
            <body className={inter.className}>
                <AppProvider initialAccessToken={accessToken}>
                    <AuthProvider>
                        <Header />
                        {children}
                    </AuthProvider>
                </AppProvider>
            </body>
        </html>
    );
}
